### ISSUE TITLE
About the licensing

### ISSUE THREAD

**Issue by Anachron** [ellisonleao/sharer.js#26]
So you let other people help building your tool (open source) but sell it alone? 

I'm asking myself where we would be if everybody would do that.

What if, for example, the jQuery team decides to do this?

**Comment by ellisonleao** [comment]
Hey @Anachron you don't have to pay if you use sharer.js on a open source project. I don't think this can compare with jquery, because they have their own way to profit from the lib despite you think it's "free".

There are a lot of other projects who act like this one:

- https://github.com/matthieua/WOW
- https://github.com/metafizzy/isotope

I hope you understand that open source != free.

I will close the issue, but if you have any more to discuss feel free to open it again. 

Thanks!

**Comment by jnareb** [comment]
I don't think you understand open source licensing.

You asking people to get commercial license to include sharer.js in closed-source products is just that: a request. You use "lax" / permissive non-copyleft MIT license. The MIT license permits reuse within proprietary (closed-source) software provided all copies of the licensed software include a copy of the MIT License terms and the copyright notice. That's all. There is no restriction in the license that you cannot use the software in closed-source projects.

If you want to provide dual licensing, you would need to choose copyleft license (like for example GPLv3 or AGPLv3), and to be really covered to require either copyright assignment, or contributor license agreement from contributors (so that code from other people can be used in the version under commercial license), Or use some license intended for dual licensing, like MPL or EPL (Mozilla Public License, or Eclipse Public License).

**Comment by ellisonleao** [comment]
@jnareb thanks for the great explanation! i will probably have to change the open source license now.

**Comment by dfyx** [comment]
Please note that GPLv3 *still* allows commercial use. It just requires the user to publish any source code that interacts directly (with a rather unintuitive definition of what that means) with the GPL licensed software.

**Comment by jnareb** [comment]
Also note that even with "strict" copyleft licenses like GPL, the requirement to use the same license for derived code apply only when the combined program is published. For AGPLv3 using product on open Internet is AFAIK also publishing, but check the license.
